/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a   wide range of models with different capabilities, performance characteristics,   and price points. Refer to the   [model guide](https://platform.openai.com/docs/models) to browse and compare   available models.
 */
/**
 * @type ChatCompletionCreateParamsNonStreamingDtoModel
 * Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a   wide range of models with different capabilities, performance characteristics,   and price points. Refer to the   [model guide](https://platform.openai.com/docs/models) to browse and compare   available models.
 * @export
 */
export type ChatCompletionCreateParamsNonStreamingDtoModel = object | string;

