/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatEntryDto { 
    /**
     * ObjectId of the owning user
     */
    userId: string;
    internalChatId: string;
    /**
     * ChatMetadata ObjectId reference
     */
    chatInternalId?: object | null;
    name?: object | null;
    createdAt: string;
    updatedAt: string;
    /**
     * Username of the user who wrote this entry (shared chats)
     */
    username?: string;
    /**
     * Rolling Chat Completions message array, when applicable
     */
    messages?: object;
}

