/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTokenLimitConfigDto { 
    minutesTillReset: number;
    tokensPerInterval: number;
    /**
     * Free-form subscription tier name. Creating a config with a new name defines a new subscription type.
     */
    subscription: string;
}

