/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAdminUserDto { 
    username: string;
    password: string;
    role?: CreateAdminUserDto.RoleEnum;
    /**
     * Any existing subscription tier name (free-form — see GET /admin/subscription-types)
     */
    subscription?: string;
    isActivated?: boolean;
}
export namespace CreateAdminUserDto {
    export const RoleEnum = {
        Admin: 'admin',
        User: 'user'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


