/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Constrains effort on reasoning for   [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently   supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`.   Reducing reasoning effort can result in faster responses and fewer tokens used   on reasoning in a response.      - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported     reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool     calls are supported for all reasoning values in gpt-5.1.   - All models before `gpt-5.1` default to `medium` reasoning effort, and do not     support `none`.   - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.   - `xhigh` is supported for all models after `gpt-5.1-codex-max`.
 */
export const ReasoningEffort = {
    Low: 'low',
    High: 'high',
    None: 'none',
    Minimal: 'minimal',
    Medium: 'medium',
    Xhigh: 'xhigh'
} as const;
export type ReasoningEffort = typeof ReasoningEffort[keyof typeof ReasoningEffort];

