/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAdminUserDto { 
    /**
     * New password — leave unset to keep the current one
     */
    password?: string;
    role?: UpdateAdminUserDto.RoleEnum;
    /**
     * Any existing subscription tier name (free-form — see GET /admin/subscription-types)
     */
    subscription?: string;
    isActivated?: boolean;
}
export namespace UpdateAdminUserDto {
    export const RoleEnum = {
        Admin: 'admin',
        User: 'user'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


