/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface URLCitationDto { 
    /**
     * The index of the last character of the URL citation in the message.
     */
    end_index: number;
    /**
     * The index of the first character of the URL citation in the message.
     */
    start_index: number;
    /**
     * The title of the web resource.
     */
    title: string;
    /**
     * The URL of the web resource.
     */
    url: string;
}

